name: qr_generator
description: A tool used for WTM HCMC team's operations.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  qr: ^3.0.0
  path_provider: 2.0.0
  open_file: ^3.2.1
  flutter_colorpicker: ^1.0.3
  dotted_border: ^2.0.0
  flutter_image_compress: ^2.0.4
  http: ^1.1.0
  image_downloader_web: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
